python main.py \
--dataset_name mimic_cxr \
--image_dir /GPUFS/nsccgz_ywang_zfd/limengfei/datasets/mimic_cxr/images/ \
--ann_path /GPUFS/nsccgz_ywang_zfd/limengfei/ReportGen/data/mimic_cxr/annotation_merged.json \
--max_seq_length 100 \
--threshold 10 \
--epochs 150 \
--gamma 0.1 \
--step_size 10 \
--batch_size 128 \
--seed 456789 \
--img_size 224 \
--n_gpu 4 \
--num_workers 16 \
--lr_ve 5e-6 \
--lr_ed 1e-5 \
--model_name noatt_mimic_bleu4 \
--save \
--resume current_mimic.pth \
--not_load_optim
