python main.py \
--dataset_name mimic_cxr \
--image_dir /GPUFS/nsccgz_ywang_zfd/limengfei/datasets/mimic_cxr/images/ \
--ann_path /GPUFS/nsccgz_ywang_zfd/limengfei/ReportGen/data/mimic_cxr/annotation_merged.json \
--max_seq_length 100 \
--threshold 10 \
--epochs 100 \
--gamma 0.8 \
--batch_size 80 \
--seed 456789 \
--img_size 224 \
--n_gpu 4 \
--num_workers 16 \
--lr_res 1e-4 \
--lr_lp 1e-4 \
--lr_ed 2e-4 \
--model_name merged2e-4g8s10bs80
